# Generated by Django 3.0.8 on 2020-07-31 21:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_author_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
